"""initial schema: accounts, publish_tasks, publish_jobs, publish_job_events

Revision ID: c5555f944e58
Revises: 
Create Date: 2026-03-20 08:45:33.253013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5555f944e58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cookie_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_test', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_platform'), 'accounts', ['platform'], unique=False)
    op.create_table('publish_job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_job_events_job_id'), 'publish_job_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_publish_job_events_task_id'), 'publish_job_events', ['task_id'], unique=False)
    op.create_table('publish_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.Float(), nullable=False),
    sa.Column('product_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('product_identity', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_publish_jobs_idempotency_key', 'publish_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_publish_jobs_status'), 'publish_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_publish_jobs_task_id'), 'publish_jobs', ['task_id'], unique=False)
    op.create_table('publish_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.Column('publish_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('publish_url', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_tasks')
    op.drop_index(op.f('ix_publish_jobs_task_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_status'), table_name='publish_jobs')
    op.drop_index('idx_publish_jobs_idempotency_key', table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_index(op.f('ix_publish_job_events_task_id'), table_name='publish_job_events')
    op.drop_index(op.f('ix_publish_job_events_job_id'), table_name='publish_job_events')
    op.drop_table('publish_job_events')
    op.drop_index(op.f('ix_accounts_platform'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
